routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
    {
        Auth::logout();
        return view('auth.login');
        
    }
    return view('auth.login');
});

Auth::routes(['active' => 1]);
    Route::resource('lich-su-giao-dich', 'TransactionHistoriesController');
    // Route::resource('sale', 'SaleController');
    Route::resource('lich-su-tu-van', 'HistoriesController');
    Route::get('/profile', 'UserController@profile')->name('profile');
    Route::put('/profileUpdate/{id}', 'UserController@profileUpdate')->name('profileUpdate');
    Route::resource('sale', 'SaleController');
// Middleware Admin
Route::group(['middleware' => 'role:Admin'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('usergroup', 'UserGroupController');
    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::resource('user', 'UserController');
    Route::resource('permission', 'PermissionController');  
    Route::resource('role', 'RoleController');
    Route::put('/activeStatus/{id}', 'UserController@activeStatus')->name('activeStatus');
 });
// Middleware Employee
Route::group(['middleware' => 'role:Employees'], function() {
    Route::resource('user-sale', 'UserSalesController');
    
});
// Route::resource('customer', 'CustomerController');
Route::get('/map', function () {
    return view('test');
});

app/Permission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Providers\PermissionsServiceProvider;

class Permission extends Model
{
    protected $fillable = [
        'slug',
        'name', 
        'created_at',
        'updated_at'
    ];
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;
use App\UsersPermission;

class PermissionController extends Controller
{
    public function __construct()
    {
       $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        if ($request->user()->can('view-all')) 
        {
            $per = Permission::get();
            return view('permission.index', compact('per', $per));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if ($request->user()->can('create')) {
            return view('user.create');
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);  
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->user()->can('create')) 
        {
            $error = Permission::where('slug', $request->slug)->first();
            if (isset($error))
            {
                $notification = array(
                    'message' => 'Tên vừa nhập đã tồn tại!',
                    'alert-type' => 'error'
                );
                return  back()->with($notification);
            }
            else
            {
                $per = Permission::create([
                    'slug' => $request['slug'], 
                    'name' => $request['name'], 
                    'created_at' =>  date('Y-m-d H:i:s'),
                    'updated_at' =>  date('Y-m-d H:i:s')
                ]);
                $notification_success = array(
                    'message' => 'Thêm thành công!',
                    'alert-type' => 'success'
                );
                return redirect('/permission')->with($notification_success);
            }
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return  back()->with($notification_error);  
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $id)
    {
        if ($request->user()->can('view')) {
            $per= Permission::where('id',$request->permission)->first();
           return view('permission.view', compact('per', $per));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return  back()->with($notification_success);  
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if ($request->user()->can('edit')) {
            $per= Permission::where('id',$request->permission)->first();
        return view('permission.edit',compact('per', $per));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
       return  back()->with($notification_error);  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->user()->can('edit'))
        {
            $per= Permission::where('id',$id)->first();
            $per->update($request->all());
            $notification = array(
                'message' => 'Cập nhật thành công!',
                'alert-type' => 'success'
            );
        return redirect('/permission')->with($notification);
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
       return back()->with($notification_error);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        if ($request->user()->can('delete')) {
            $per= Permission::findOrFail($request->id);
            $error_per = UsersPermission::where('permission_id', $per->id)->first();
            if (isset($error_per))
            {
                $notification_error = array(
                    'message' => 'Vui lòng xóa quyền này của người dùng trước khi xóa nhóm quyền!',
                    'alert-type' => 'error'
                );
                return back()->with($notification_error);
            }
            else
            {
                $per->delete();
                $notification = array(
                    'message' => 'Xóa bỏ thành công!',
                    'alert-type' => 'success'
                );
                return back()->with($notification);
            }
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }
}

resources/views/permission/create.blade.php
<div class="modal fade" id="modalCreateForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header card-primary">
            <!-- <h4 class="modal-title w-100 font-weight-bold">Sign up</h4> -->
            <h3 class="card-title modal-title w-100 font-weight-bold">{{ __('permission.per_create') }}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body mx-3">
      <form method="post" action="{{ route('permission.store') }}">
        @csrf
        @method('POST')
        <div class="md-form mb-3">
            <label for="slug">{{ __('permission.permission_name') }}</label>
            <input id="slug" type="text" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}" name="slug" value="{{ old('slug') }}" autofocus>
        </div>
        <div class="md-form mb-3">
            <label for="name">{{ __('permission.note') }}</label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" autofocus>
        </div>
      <div class="modal-footer d-flex justify-content-center">
        <button type="submit" class="btn btn-success">
            <i class="fa fa-save" aria-hidden="true"></i>
            {{ __('permission.save') }}
        </button>
        <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
            <i class="fa fa-times" aria-hidden="true"></i>
            {{ __('permission.cancel') }}
        </button>
      </div>
      </form>
    </div>
  </div>
</div>

resources/views/permission/delete.blade.php
<div class="modal fade" id="confirm{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body " style="background-image: url({{ asset('dist/img/delete.jpg') }}); background-repeat: no-repeat; background-size: 130px; padding-left: 130px;">
        <h3 class="card-title modal-title w-100" style="margin-bottom: 20px;">{{ __('user.delete_user') }}</h3>
        <form method="post" action="{{ route('user.update', $user->id) }}">
            @csrf
            @method('DELETE')
            <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
            <i class="fa fa-times" aria-hidden="true"></i>
                {{ __('user.cancel') }}
            </button>
            <button type="submit" class="btn btn-danger">
                <i class="fa fa-trash" aria-hidden="true"></i>
                    {{ __('user.delete') }}
            </button>
        </form>
        </div>
    </div>
  </div>
</div>

resources/views/permission/edit.blade.php
@extends('layouts.master')
@section('title')
 {{ __('users.permission')  }}
@stop
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.permission')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.permission') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
             <h3 class="card-title">{{ __('permission.permission_edit') }}:{{$per->name}}</h3>
            </div>  
            <!-- /.card-header -->
            <div class="card-body">
                <form method="post" action="{{ route('permission.update', $per->id) }}">
                  @csrf
                  @method('PUT')
                  <div class="form-group" style="width:auto; margin-top: -15px; margin-bottom: -10px;" >
                    <button type="button" class="btn btn-outline-secondary">
                        <a style="text-decoration: none; color: black;" href="{{ route('permission.index') }}">
                          <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('permission.back') }}
                        </a>
                    </button>
                  </div>
                  <hr />
                  <div class="container col-md-6">
                    <div class="form-group ">
                      <label for="slug">{{ __('permission.permission_name') }}</label>
                      <input readonly type="text" class="form-control" name="slug" id="slug" value="{{ old('slug', $per->slug) }}">
                    </div>
                    <div class="form-group">
                      <label for="name">{{ __('permission.note') }}</label>
                      <input type="text" class="form-control" name="name" id="name" value="{{ old('name', $per->name)}}">
                    </div>
                  </div> 
                  <div style="text-align: center;"> 
                      <button type="reset" class="btn btn-outline-secondary">
                        <i class="fa fa-times" aria-hidden="true"></i>{{ __('users.cancel') }}
                      </button>
                      <button type="submit" class="btn btn-success">
                        <i class="fa fa-save" aria-hidden="true"></i> {{ __('users.save') }}
                      </button>
                  </div>
                </form>
            </div>
            <!-- /.card-body -->
        </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
<!-- /.content-wrapper -->
@endsection

resources/views/permission/index.blade.php
@extends('layouts.master')
@section('title')
 {{ __('users.permission')  }}
@stop

@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.permission')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.permission') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ __('users.permission') }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div style="width:auto">
                <button type="button" data-toggle="modal" data-target="#modalCreateForm" type="button" class="btn btn-outline-secondary ">
                <i class="fa fa-plus" aria-hidden="true"></i> {{ __('permission.per_create') }}
                </button>
                <button type="button" class="btn btn-outline-secondary ">
                  <i class="fa fa-refresh" aria-hidden="true" data-toggle="tooltip" title="Làm mới"></i>
                </button>
              </div>
              <br />
              <table id="tableData" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                <thead>
                <tr>
                  <th>{{ __('permission.permission_name') }}</th>
                  <th>{{ __('permission.note') }}</th>
                  <th>{{ __('permission.created_at') }}</th>
                  <th>{{ __('permission.updated_at') }}</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($per as $per)
                <tr>
                  <td>{{$per->slug }}</td>
                  <td>{{$per->name}}</td>
                  <td>{{ date('d/m/Y H:i:s', strtotime($per->created_at)) }} </td>
                  <td>{{ date('d/m/Y H:i:s', strtotime($per->updated_at)) }}</td>
                  <td>
                    <a href="{{ route('permission.edit',$per->id) }}"> 
                      <i data-toggle="tooltip" title="Chỉnh sửa" style="text-align: right;" class="	fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>  
                    | 
                    <a href="javascript(0);" onclick="deleteData({{$per->id}})" data-toggle="modal" data-target="#confirm" > 
                      <i data-toggle="tooltip" style="color:red " title="Xóa" style="text-align: right;" class="fa fa-trash-o" aria-hidden="true" ></i>
                    </a>
                  </td>
                </tr>
                <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-body " style="background-image: url({{ asset('dist/img/delete.jpg') }}); background-repeat: no-repeat; background-size: 130px; padding-left: 130px;">
                          <h3 class="card-title modal-title w-100" style="margin-bottom: 20px;">{{ __('permission.per_del') }}</h3>
                          <form method="post" id="deleteForm" action="">
                              @csrf
                              @method('DELETE')
                              <input type="hidden" name="id" id="id">
                              <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
                              <i class="fa fa-times" aria-hidden="true"></i>
                                  {{ __('users.cancel') }}
                              </button>
                              <button data-dismiss="modal" onclick="formSubmit()"  name="" type="submit" class="btn btn-danger">
                                  <i class="fa fa-trash" aria-hidden="true"></i>
                                      {{ __('permission.delete') }}
                              </button>
                          </form>
                          </div>
                      </div>
                    </div>
                  </div>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
<!-- /.content-wrapper -->
@include('permission.create')
<!-- /.modal -->
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
@endpush

@push('js')
<script type="text/javascript">
  function deleteData(id)
   {
      var id = id;
      var url = '{{ route("permission.destroy", ":id") }}';
      url = url.replace(':id', id);
      $("#id").val(id);
      $("#deleteForm").attr('action', url);
    }

     function formSubmit()
     {
        $("#deleteForm").submit();
     }
     
</script>
@endpush

resources/views/permission/view.blade.php
@extends('layouts.master')
@section('title')
 {{ __('users.permission')  }}
@stop
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.permission')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.permission') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
        <div class="card">
            <div class="card-header">
             <h3 class="card-title">Xem quyền: {{$per->name}}</h3>
            </div>  
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group" style="width:auto; margin-top: -15px; margin-bottom: -10px;" >
                <button type="button" class="btn btn-outline-secondary">
                    <a style="text-decoration: none; color: black;" href="{{ redirect()->getUrlGenerator()->previous() }}">
                      <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('users.back') }}
                    </a>
                </button>
              </div>
                  <hr />   
              <table style="margin-left:20px;width:700px">
                <tr>
                  <td style="width:150px;padding:5px"><b>Tên quyền</b></td>
                  <td>{{$per->slug}}</td>
                </tr>
                <tr>
                  <td style="width:150px;padding:5px"><b>Chú thích</b></td>
                  <td>{{$per->name}}</td>
                </tr>

              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
<!-- /.content-wrapper -->
@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
@endpush
@push('js')
<!-- DataTables -->
<script src="{{ asset('plugins/datatables/jquery.dataTables.js') }}"></script>
<script src="{{ asset('plugins/datatables/dataTables.bootstrap4.js') }}"></script>
@endpush