routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
    {
        Auth::logout();
        return view('auth.login');
        
    }
    return view('auth.login');
});

Auth::routes(['active' => 1]);
    Route::resource('lich-su-giao-dich', 'TransactionHistoriesController');
    // Route::resource('sale', 'SaleController');
    Route::resource('lich-su-tu-van', 'HistoriesController');
    Route::get('/profile', 'UserController@profile')->name('profile');
    Route::put('/profileUpdate/{id}', 'UserController@profileUpdate')->name('profileUpdate');
    Route::resource('sale', 'SaleController');
// Middleware Admin
Route::group(['middleware' => 'role:Admin'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('usergroup', 'UserGroupController');
    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::resource('user', 'UserController');
    Route::resource('permission', 'PermissionController');  
    Route::resource('role', 'RoleController');
    Route::put('/activeStatus/{id}', 'UserController@activeStatus')->name('activeStatus');
 });
// Middleware Employee
Route::group(['middleware' => 'role:Employees'], function() {
    Route::resource('user-sale', 'UserSalesController');
    
});
// Route::resource('customer', 'CustomerController');
Route::get('/map', function () {
    return view('test');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'category_id',
        'ward_id',
        'user_id',
        'product_name',
        'alias',
        'avatar',
        'alt',
        'images',
        'summary',
        'content',
        'price',
        'acreage',
        'area',
        'length',
        'width',
        'direction',
        'status',
        'lat',
        'lng',
        'note',
            
    ];
    
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\StoreProduct;
use App\Product;
use App\History;
use Carbon\Carbon;
use Auth;
use Validator;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->user()->can('view-all')) {
            $products = Product::get();
            return view('product.index',compact('products', $products));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if ($request->user()->can('create')) {
        return view('product.create');
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->user()->can('create')) {
         // validation
        $messages = [
            'category_id.required'  => __('product.category_id') .' là bắt buộc',
            'ward_id.required'      => __('product.ward_id') . ' là bắt buộc',
            // 'user_id.required'      => __('product.user_id') . ' là bắt buộc',
            'product_name.required' => __('product.product_name') . ' là bắt buộc',
            'alias.required'        => __('product.alias') . ' là bắt buộc',
            'acreage.required'      => __('product.acreage') . ' là bắt buộc',
            'direction.required'    => __('product.acreage') . ' là bắt buộc',
            'status.required'       => __('product.status') . ' là bắt buộc',
        ];
        $validator = Validator::make($request->all(), [
            'category_id'       => 'required',
            'ward_id'           => 'required',
            // 'user_id'           => 'required',
            'product_name'      => 'required|max:191',
            'alias'             => 'required',
            'avatar'            => '',
            'alt'               => '',
            'images'            => '',
            'summary'           => '',
            'content'           => '',
            'price'             => '',
            'acreage'           => 'required',
            'area'              => '',
            'length'            => '',
            'width'             => '',
            'direction'         => 'required',
            'status'            => 'required',
            'lat'               => '',
            'lng'               => '',
            'note'              => '',
        ], $messages );
        
        if ($validator->fails()) {
            return redirect('product/create')
                        ->withErrors($validator)
                        ->withInput();
        }
        // and validation
        // $error_price = $request->price;
        //validation price
        // if ( $error_price <= 1000000 || $error_price <0 || $error_price >=100000000000000 )
        // {
        //     $notification = array(
        //         'message' => 'Giá trị phải >=1.000.000 và lớn hơn 0 và <=100.000.000.000.000!',
        //         'alert-type' => 'error'
        //     );
        //     return redirect('product/create')->with($notification);
        // }
        // end validation price
        // check product_name and $request->file('avatar') and create Product
        $error = Product::where('product_name', $request->product_name)->first();
        
        if(isset($error_avatar))
        {
            $notification = array(
                'message' => 'Ảnh đại diện đã tồn tại!',
                'alert-type' => 'error'
            );
        } 
        if (isset($error))
        {
            $notification = array(
                'message' => 'Tên vừa nhập đã tồn tại!',
                'alert-type' => 'error'
            );
        }
        else
        {
            //check $request->file('avatar')
            $avatar = $request->file('avatar');
            // $avatar_add = 'uploads/images/' . $avatar->getClientOriginalName();
            // $error_avatar = Product::where('avatar', $avatar_add)->first();
            if (empty($avatar))
            {
                $avatar_add = '';
            }
            else
            {
                $destinationPath = base_path() . '/public/uploads/images/';
                $avatar->move($destinationPath, $avatar->getClientOriginalName());
                $avatar_add = 'uploads/images/' . $avatar->getClientOriginalName();
            }
            //end check $request->file('avatar')
            //create product
            $product = Product::create([
                'category_id'       => $request->category_id,
                'ward_id'           => $request->ward_id,
                'user_id'           => Auth::id(),
                'product_name'      => $request->product_name,
                'alias'             => $request->alias,
                'avatar'            => $avatar_add,
                'alt'               => $request->alt,
                'images'            => $request->images,
                'summary'           => $request->summary,
                'content'           => $request->content,
                'price'             => $request->price,
                'acreage'           => $request->acreage,
                'area'              => $request->area,
                'length'            => $request->length,
                'width'             => $request->width,
                'direction'         => $request->direction,
                'status'            => $request->status,
                'lat'               => $request->lat,
                'lng'               => $request->lng,
                'note'              => $request->note,
            ]);
            //end create 
            $notification = array(
                'message' => 'Thêm mới thành công!',
                'alert-type' => 'success'
            );
           
        }
        return redirect('/product')->with($notification);
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function show(Request $request, $alias)
    {
        if ($request->user()->can('view')) {
        $product = Product::where('alias', $alias)->first();
        return view('product.show', compact('product'));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if ($request->user()->can('edit')) 
        {
            $product = Product::where('id', $id)->first();
            if ($product->status != 1)
            {
                $notification_error = array(
                    'message' => 'Vui lòng không chỉnh sửa thông tin khi mảnh đất đã bán hoặc đang tư vấn!',
                    'alert-type' => 'error'
                );
                return back()->with($notification_error);
            }
            else
            {
                return view('product.edit', compact('product'));
            }
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->user()->can('edit')) 
        {
        // validation
        $messages = [
            'category_id.required'  => __('product.category_id') .' là bắt buộc',
            'ward_id.required'      => __('product.ward_id') . ' là bắt buộc',
            // 'user_id.required'      => __('product.user_id') . ' là bắt buộc',
            'product_name.required' => __('product.product_name') . ' là bắt buộc',
            'alias.required'        => __('product.alias') . ' là bắt buộc',
            'acreage.required'      => __('product.acreage') . ' là bắt buộc',
            'direction.required'    => __('product.direction') . ' là bắt buộc',
            'status.required'       => __('product.status') . ' là bắt buộc',
        ];
        $validator = Validator::make($request->all(), [
            'category_id'       => 'required',
            'ward_id'           => 'required',
            // 'user_id'           => 'required',
            'product_name'      => 'required|max:191',
            'alias'             => 'required',
            'avatar'            => '',
            'alt'               => '',
            'images'            => '',
            'summary'           => '',
            'content'           => '',
            'price'             => '',

resources/views/product/create.blade.php
@extends('layouts.master')

@section('title')
 {{ __('product.create_product')  }}
@stop 
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper" onload="initialize();">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.real_estate_management')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.product') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ __('product.create_product')  }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <form method="post" action="{{ route('product.store') }} " enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                <div class="form-group" style="width:auto; margin-top: -15px; margin-bottom: -10px;" >
                    <button type="button" class="btn btn-outline-secondary">
                        <a style="text-decoration: none; color: black;" href="{{ url()->previous() }}">
                            <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('product.back') }}</a>
                    </button>
                    <div style="right: 0; margin-top: -35px; margin-bottom: -10px; text-align: right;"> 
                    <button type="reset" class="btn btn-outline-secondary">
                          <i class="fa fa-times" aria-hidden="true"></i>
                              {{ __('product.cancel') }}
                      </button>
                      <button type="submit" class="btn btn-success">
                          <i class="fa fa-save" aria-hidden="true"></i>
                              {{ __('product.save') }}
                      </button>
                    </div>
                </div>
			          <hr />
                <div class="container" style="margin-left: -10px;" >
                      @include('product.form.create')
                </div>
                </form>
			      </div>
            
            <!-- card-body -->
			    </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')

@section('title')
 {{ $product->product_name }}
@stop 
@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.real_estate_management')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.product') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ $product->product_name }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            <form method="post" action="{{ route('product.update', $product->id) }} " enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group" style="width:auto; margin-top: -15px; margin-bottom: -10px;" >
                    <button type="button" class="btn btn-outline-secondary">
                        <a style="text-decoration: none; color: black;" href="{{ redirect()->getUrlGenerator()->previous() }}">
                            <i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('product.back') }}</a>
                    </button>
                    <div style="right: 0; margin-top: -35px; margin-bottom: -10px; text-align: right;"> 
                    <button type="reset" class="btn btn-outline-secondary">
                          <i class="fa fa-times" aria-hidden="true"></i>
                              {{ __('product.cancel') }}
                      </button>
                      <button type="submit" class="btn btn-success">
                          <i class="fa fa-save" aria-hidden="true"></i>
                              {{ __('product.save') }}
                      </button>
                    </div>
                </div>
			          <hr />
                <div class="container" style="margin-left: -10px;" >
                    @include('product.form.edit')
                </div>
			      </div>
            </form>
            <!-- card-body -->
			</div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@endsection

resources/views/product/index.blade.php
@extends('layouts.master')
@section('title')
 {{ __('users.product')  }}
@stop
@php
  function number_formatting($n) {
    // first strip any formatting;
    $n = (0+str_replace(",","",$n));
        
    // is this a number?
    if(!is_numeric($n)) return false;
        
    // now filter it;
    if($n>1000000000) return round(($n/1000000000),1).' tỷ';
    else if($n>1000000) return round(($n/1000000),1).' triệu';
    else if($n>1000) return round(($n/1000),1).' ngàn';
        
    return number_format($n);
    }
@endphp
@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.real_estate_management')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.product') }}</li>
            </ol>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ __('users.product') }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div style="width:auto">
                <button type="button" class="btn btn-outline-secondary">
                  <a style="text-decoration: none; color: black;" href="{{ route('product.create') }}" > 
                  <i class="fa fa-plus" aria-hidden="true"></i> {{ __('product.add') }}
                  </a>
                </button>
                <!-- <button id="refresh" type="button" class="btn btn-outline-secondary">
                  <i  class="fa fa-refresh" aria-hidden="true" data-toggle="tooltip" title="Làm mới"></i>
                </button> -->
              </div>
              <br />
              <table id="tableData" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                <thead>
                <tr>
                  <th style="width:250px">{{ __('product.product_name') }}</th>
                  <th style="width:65px">{{ __('product.avatar') }}</th>
                  <th style="width:120px">{{ __('product.category_id') }}</th>
                  <th style="width:65px">{{ __('product.price') }}</th>
                  <th style="width:70px">{{ __('product.status') }}</th>
                  <th style="width:70px">{{ __('product.acreage') }}</th>
                  <th style="width:115px">{{ __('product.user_id') }}</th>
                  <th style="width:55px">{{ __('product.action') }}</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($products as $product)
                    @php
                      $name = \App\User::where('id', $product->user_id)->first();
                      $category = \App\Category::where('id',$product->category_id)->first();
                    @endphp
                  <tr>
                    <td>{{ $product->product_name }}</td>
                    <td>
                      @if (empty($product->avatar))
                        <img src="{{ asset('uploads/images/no_image_available.jpeg') }}" style="width:120px; height:120px"  />
                      @else
                        <img src="{{ url($product->avatar)}}" style="width:120px; height:120px" />
                      @endif
                    </td>
                    
                    <td>{{ $category->category_name }}</td>
                    <td>
                    @if (isset($product->price))
                        {{ number_format($product->price, 0) }} VND 
                    @else
                      <span class="badge bg-success">
                        {{ __('Thỏa thuận') }}
                      </span>
                    @endif
                    </td>
                    <td style="font-size:18px;">
                    @if ($product->status == 1)
                      <span class="badge bg-info">
                        {{ __('Đang bán') }}
                      </span>
                    @elseif ($product->status == 2)
                      <span class="badge bg-success">
                        {{ __('Đã bán') }}
                      </span>
                    @elseif ($product->status == 3)
                      <span class="badge bg-warning">
                        {{ __('Đang tư vấn') }}
                      </span>
                    @endif
                    </td>
                    <td>{{ $product->acreage }} m<sup>2</sup> </td>
                    <td>{{ $name->fullname }}</td>
                  <td > 
                    <a  href="{{ route('product.show', $product->alias) }}" > 
                      <i data-toggle="tooltip" title="Xem chi tiết" style="text-align: right;" class="fa fa-eye" aria-hidden="true"></i>
                    </a>
                    | 
                    <a  href="{{ route('product.edit', $product->id) }}" > 
                      <i data-toggle="tooltip" title="Chỉnh sửa" style="text-align: right;" class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a> 
                    |
                    <a href="javascript(0);" style="color:red" data-toggle="modal" data-target="#confirm{{$product->id}}" > 
                      <i data-toggle="tooltip" title="Xóa" style="text-align: right;" class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                  </td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
</div>
<!-- /.content-wrapper -->
<!-- Modal -->
@foreach ($products as $product)
<div class="modal fade" id="confirm{{ $product->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body " style="background-image: url({{ asset('dist/img/delete.jpg') }}); background-repeat: no-repeat; background-size: 130px; padding-left: 130px;">
        <h3 class="card-title modal-title w-100" style="margin-bottom: 20px;">{{ __('product.delete_product') }}</h3>
        <h6>Bất động sản: {{ $product->product_name }}</h6>
        <form method="post" action="{{ route('product.destroy', $product->id) }}">
            @csrf
            @method('DELETE')
            <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
            <i class="fa fa-times" aria-hidden="true"></i>
                {{ __('product.cancel') }}
            </button>
            <button type="submit" class="btn btn-danger">
                <i class="fa fa-trash" aria-hidden="true"></i>
                    {{ __('product.delete') }}
            </button>
        </form>
        </div>
    </div>
  </div>
</div>
@endforeach
<!-- /.modal -->
@endsection

resources/views/product/show.blade.php
@extends('layouts.master')

@section('title')
 {{ $product->product_name  }}
@stop 
@php
function get_address($ward_id)
   {
		$ward = \App\Ward::where('id', $ward_id)->first();
		$district = \App\District::where('id', $ward->district_id)->first();
		$town = \App\Town::where('id', $district->town_id)->first();
		$address = $ward->ward_name .', '. $district->district_name .', '. $town->town_name ;
		return $address;
   }
function get_category($category_id)
	{
		$category = \App\Category::where('id', $category_id)->first();
		return $category->category_name;
	}
@endphp


@section('content')
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.real_estate_management')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
							<li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.product') }}</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ $product->product_name }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
					<div class="form-group" style="width:auto; margin-top: -15px; margin-bottom: -10px;" >
						<button type="button" class="btn btn-outline-secondary">
							<a style="text-decoration: none; color: black;" href="{{ route('product.index') }}">
								<i class="fa fa-arrow-left" aria-hidden="true"></i> 
								{{ __('Trở lại') }}
							</a>
						</button>
										
					</div>
					<!-- <div style="right: 0; margin-top: -35px; margin-bottom: -10px; text-align: right;"> 
						<button type="button" class="btn btn-outline-secondary">
							<a style="text-decoration: none; color: black; text-align:right" href="{{ route('sale.index') }}">
								<i class="fa fa-arrow-left" aria-hidden="true"></i> 
								{{ __('Trở lại bản đồ') }}
							</a>
						</button>
            </div> -->
					<hr />
					<div class="container" style="margin-left: -10px;" >
					<div class="row">
						<div class="col-6">
							<div class="form-group">
								<b>{{ __('product.category_id') }}: </b>{{ get_category($product->category_id) }}
							</div>
							<div class="form-group">
								<b>{{ __('product.ward_id') }}: </b> 
								{{ get_address($product->ward_id) }}
							</div>
							<div class="form-group">
								<b>{{ __('product.price') }}: </b>
								@if (isset($product->price))
									{{ number_format($product->price, 0) }} VND 
								@else
									<span class="badge bg-success">
											{{ __('Thỏa thuận') }}
									</span>
								@endif
							</div>
							<div class="form-group">
								<b>{{ __('product.acreage') }}: </b>{{ $product->acreage }} m<sup>2</sup>
							</div>

							<div class="form-group" >
								<b>{{ __('product.direction') }}: </b>
								@foreach (__('product.directions') as $key => $drt )
									@if ($key == $product->direction)
										{{ $drt['vi'] . ' (' . $drt['en'] . ')' }}
										@endif
								@endforeach
							</div>

							<div class="form-group">
								<b>{{ __('product.content') }}: </b>
								<div>
									{!! $product->content !!}
								</div>
							</div>
						</div>

					<div class="col-6">
						<div class="form-group" >
							<label for="area">{{ __('Vị trí bản đồ') }}</label>
							@include('product.form.showmap')
						</div>
					</div>
				</div>
				</div>
				</div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
@endsection