routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check())
    {
        Auth::logout();
        return view('auth.login');
        
    }
    return view('auth.login');
});

Auth::routes(['active' => 1]);
    Route::resource('lich-su-giao-dich', 'TransactionHistoriesController');
    // Route::resource('sale', 'SaleController');
    Route::resource('lich-su-tu-van', 'HistoriesController');
    Route::get('/profile', 'UserController@profile')->name('profile');
    Route::put('/profileUpdate/{id}', 'UserController@profileUpdate')->name('profileUpdate');
    Route::resource('sale', 'SaleController');
// Middleware Admin
Route::group(['middleware' => 'role:Admin'], function() {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('usergroup', 'UserGroupController');
    Route::resource('category', 'CategoryController');
    Route::resource('product', 'ProductController');
    Route::resource('user', 'UserController');
    Route::resource('permission', 'PermissionController');  
    Route::resource('role', 'RoleController');
    Route::put('/activeStatus/{id}', 'UserController@activeStatus')->name('activeStatus');
 });
// Middleware Employee
Route::group(['middleware' => 'role:Employees'], function() {
    Route::resource('user-sale', 'UserSalesController');
    
});
// Route::resource('customer', 'CustomerController');
Route::get('/map', function () {
    return view('test');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\HasPermissionsTrait;

class User extends Authenticatable
{
    use Notifiable, HasPermissionsTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'fullname',
        'username',
        'password',
        'pass_first',
        'avatar',        
        'gender',
        'birthday',
        'phone',
        'email',
        'address',
        'active',
        'attribs',
        'last_login',
        'protected',
        'created_by',
        'note',
        'created_at',
        'updated_at',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function users()
    {
        return $this->belongsToMany('App\User');
    }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Contracts\Encryption\DecryptException;
use App\User;
use App\UsersRole;
use App\UsersPermission;
use App\Role;
use App\Permission;
use Carbon\Carbon;
use Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Crypt;

class UserController extends Controller
{

    public function __construct()
    {
       $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request) {
        if ($request->user()->can('view-all')) {
            $users = User::get();
            $role = Role::get();
            $per = Permission::get();
            return view('user.index',array('per'=> $per,'users'=> $users,'role'=> $role));

        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    { 
        if ($request->user()->can('create')) {
            $role = Role::get();
            $per = Permission::get();
            return view('user.create', compact('role', $role),compact('per', $per));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->user()->can('create')) {
            $error = User::where('username', strtolower($request->username))->first();
            $per_id = $request->id_per;
            if (empty($per_id))
            {
                $notification_error = array(
                    'message' => 'Vui lòng chọn một quyền trong nhóm quyền.',
                    'alert-type' => 'error'
                );
                return back()->with($notification_error);
            }
            if (isset($error))
            {
                $notification_error = array(
                    'message' => 'Tên đăng nhập đã được sử dụng! Vui lòng chọn tên khác.',
                    'alert-type' => 'error'
                );
                return back()->with($notification_error);
            }
            else
            {
                $user = User::create([
                    'username' => $request['username'],
                    'email' => $request['email'],
                    'password' => Hash::make($request['pass_first']),
                    'pass_first' => $request['pass_first'],
                    'active' =>$request['active'],
                    'fullname' => $request['fullname'],
                    'created_by' => Auth::id(),
                ]);
                $user_id= User::where('username',$request->username)->value('id');
                $user_role = UsersRole::create([
                    'user_id' => $user_id, 
                    'role_id' => $request['id_role'], 
                    'created_at' =>  date('Y-m-d H:i:s'),
                    'updated_at' =>  date('Y-m-d H:i:s')
                ]);
                
                $per_id=$request->id_per;
                foreach($per_id as $key =>$val){
                $user_permission = UsersPermission::create([
                        'user_id' => $user_id, 
                        'permission_id' => $val, 
                        'created_at' =>  date('Y-m-d H:i:s'),
                        'updated_at' =>  date('Y-m-d H:i:s')
                    ]);
                }
                $notification = array(
                    'message' => 'Thêm mới thành công!',
                    'alert-type' => 'success'
                );
                return back()->with($notification);
            }
            
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        if ($request->user()->can('view')) {
            $user= User::where('id',$request->user)->first();
            return view('user.view', compact('user', $user));
        } 
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    public function profile(Request $request)
    {
        if ($request->user()->can('view-profile')) {
            $user= User::where('id', \Auth::id())->first();
            return view('user.profile', compact('user', $user));
        } 
        $notification_error = array(
            'message' => 'Bạn không có quyền! Vui lòng liên hệ với Admin để cập nhật thêm quyền.',
            'alert-type' => 'error'
        );
        return back()->with($notification_error);
    }

    public function profileUpdate(Request $request, $id)
    {
        //  dd($request->birthday);
        if ($request->user()->can('edit-profile')) {
            // dd($request->birthday);
            // $birth = Carbon::create($request->birthday);
            $year = date('Y', strtotime($request->birthday));
            if ($year <= 1970) 
            {
                $notification = array(
                    'message' => 'Vui lòng chọn lại năm lơn hơn 1970!',
                    'alert-type' => 'info'
                );
                return redirect('/profile')->with($notification);
            }
            else
            {
                $birth = date("Y-m-d", strtotime($request->birthday));
                // dd(Carbon::now()->toDateString());
                $request->merge([
                    'birthday' => $birth,
                ]);
                $user= User::where('id',$id)->first();
                $user->update($request->all());
                $notification = array(
                    'message' => 'Cập nhật thành công!',
                    'alert-type' => 'success'
                );
                return redirect('/profile')->with($notification);
            }
        }
        else
        {
            $notification_error = array(
                'message' => 'Bạn không có quyền! Vui lòng liên hệ với Admin để cập nhật thêm quyền.',
                'alert-type' => 'error'
            );
            return back()->with($notification_error);
        }
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        if ($request->user()->can('edit')) 
        {
            $user= User::where('id',$request->user)->first();
            $per = Permission::get();
            return view('user.edit',compact('user','per' ));
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
       return back()->with($notification_error);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($request->user()->can('edit')) {
            $birthday = date("Y-m-d", strtotime($request->birthday));
            // dd($birthday);
            $request->merge([
                'birthday' => $birthday,
            ]);
            $user= User::where('id',$id)->first();
            $user->update($request->all());
            
            $notification = array(
                'message' => 'Cập nhật thành công!',
                'alert-type' => 'success'
            );
            return redirect('/user')->with($notification);
        }
        $notification_error = array(
                'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
                'alert-type' => 'error'
            );    
       return back()->with($notification_error);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if ($request->user()->can('delete')) {
            $user = User::findOrFail($request->id);
            if ($user->id == Auth::id())
            {
                $notification_error = array(
                    'message' => 'Bạn không có quyền xóa tài khoản của chính mình.',
                    'alert-type' => 'error'
                );
                return back()->with($notification_error);
            }
            else
            {
                $user->delete();
                $notification = array(
                    'message' => 'Xóa bỏ thành công!',
                    'alert-type' => 'success'
                );
                return back()->with($notification);
            }
            
        }
        $notification_error = array(
            'message' => 'Bạn không có quyền! Thao tác này chỉ Admin mới được dùng.',
            'alert-type' => 'error'
        );
        return  back()->with($notification_error);
    }

    public function activeStatus(Request $request, $id)
    {
        if ($request->user()->can('edit'))
        {

resources/views/user/create.blade.php
<div class="modal fade" id="modalCreateForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header card-primary">
            <!-- <h4 class="modal-title w-100 font-weight-bold">Sign up</h4> -->
            <h3 class="card-title modal-title w-100 font-weight-bold">{{ __('users.user_create') }}</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body mx-3">
      <form method="post" action="{{ route('user.store') }}">
        @csrf
        @method('POST')
        <div class="md-form mb-3">
            <label for="username">{{ __('users.username') }} <sup class="text-danger">(*)</sup></label>
            <input required id="username" type="text" class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username" value="{{ old('username') }}" autofocus>
        </div>
        <div class="md-form mb-3">
            <label for="fullname">{{ __('users.fullname') }} <sup class="text-danger">(*)</sup></label>
            <input required id="fullname" type="text" class="form-control{{ $errors->has('fullname') ? ' is-invalid' : '' }}" name="fullname" value="{{ old('fullname') }}" autofocus>
        </div>
        <div class="md-form mb-3">
            <label for="pass_first">{{ __('users.password') }} <sup class="text-danger">(*)</sup></label>
            <input required id="pass_first" type="password" class="form-control{{ $errors->has('pass_first') ? ' is-invalid' : '' }}" name="pass_first" value="{{ old('pass_first') }}" autofocus>
       </div> 
       <div class="md-form mb-3">
            <label for="id_role">{{ __('users.role') }} <sup class="text-danger">(*)</sup></label>
            <select id="id_role" type="text" class="form-control{{ $errors->has('id_role') ? ' is-invalid' : '' }}" name="id_role" autofocus>
              @foreach($role as $role)
              <option required value="{{$role->id}}">{{$role->slug}}</option>
              @endforeach
            </select>
       </div> 
       <div class="md-form mb-3" >
            <label for="id_per">{{ __('users.permission') }} <sup class="text-danger">(*)</sup></label>
            <br>
            @foreach($per as $per)
             <label class="checkbox-inline" >
              <input type="checkbox" name="id_per[]" value="{{$per->id}}" style="width:45px">{{$per->name}}
            </label>
            @endforeach
       </div> 
        <div class="md-form mb-3">
            <label for="active">{{ __('users.active') }} <sup class="text-danger">(*)</sup></label>
            <input required name="active" type="radio" value="1"/> {{ __('users.active_status')}}
            <input required name="active" type="radio" value="0"/> {{ __('users.not_active')}}
        </div>
      <div class="md-form mb-3">
            <label for="email">{{ __('users.email') }} <sup class="text-danger">(*)</sup></label>
            <input required id="email" type="email"  class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" autofocus>
        </div>
      <div class="modal-footer d-flex justify-content-center">
        <button type="submit" class="btn btn-success">
            <i class="fa fa-save" aria-hidden="true"></i>
            {{ __('users.save') }}
        </button>
        <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
            <i class="fa fa-times" aria-hidden="true"></i>
            {{ __('users.cancel') }}
        </button>
      </div>
      </form>
    </div>
  </div>
</div>

resources/views/user/delete.blade.php
<div class="modal fade" id="confirm{{ $user->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body " style="background-image: url({{ asset('dist/img/delete.jpg') }}); background-repeat: no-repeat; background-size: 130px; padding-left: 130px;">
        <h3 class="card-title modal-title w-100" style="margin-bottom: 20px;">{{ __('user.delete_user') }}</h3>
        <form method="post" action="{{ route('user.update', $user->id) }}">
            @csrf
            @method('DELETE')
            <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
            <i class="fa fa-times" aria-hidden="true"></i>
                {{ __('user.cancel') }}
            </button>
            <button type="submit" class="btn btn-danger">
                <i class="fa fa-trash" aria-hidden="true"></i>
                    {{ __('user.delete') }}
            </button>
        </form>
        </div>
    </div>
  </div>
</div>

resources/views/user/index.blade.php
@extends('layouts.master')
@section('title')
 {{ __('users.user')  }}
@stop

@php
  function arr_permission($user_id)
  {
    $permissions = App\User::join('users_permissions', 'users.id', '=', 'users_permissions.user_id')
            ->join('permissions', 'users_permissions.permission_id', '=', 'permissions.id')
            ->where('users.id', $user_id)
            ->select('permissions.name')
            ->get();
    return $permissions;
  }
  function arr_role($user_id)
  {
    $roles = App\User::join('users_roles', 'users.id', '=', 'users_roles.user_id')
            ->join('roles', 'users_roles.role_id', '=', 'roles.id')
            ->where('users.id', $user_id)
            ->select('roles.name')
            ->get();
    return $roles;
  }

  function user_name($user_id)
    {
        $user_name = \App\User::where('id', $user_id)->first();
        return $user_name->fullname;
    }

@endphp

@section('content')
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{{ __('users.user_management')}}</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('home') }}">{{ __('users.home') }}</a></li>
              <li class="breadcrumb-item active">{{ __('users.user') }}</li>
            </ol>
          </div>
        </div>
      </div>
      <!-- /.container-fluid -->
    </section>
<!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ __('users.user') }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <div style="width:auto">
                <button type="button" data-toggle="modal" data-target="#modalCreateForm" type="button" class="btn btn-outline-secondary ">
                <i class="fa fa-plus" aria-hidden="true"></i> {{ __('users.user_create') }}
                </button>
              </div>
              <br />
              <table id="tableData" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                <thead>
                <tr>
                  <!-- <th>{{ __('users.avatar') }}</th> -->
                  <th>{{ __('users.fullname') }}</th>
                  <th>{{ __('users.username') }}</th>
                  <!-- <th style="width:120px">{{ __('users.permission') }}</th> -->
                  <th>{{ __('users.role') }}</th>
                  <!-- <th>{{ __('users.gender') }}</th> -->
                  <th>{{ __('users.email') }}</th>
                  <th>{{ __('users.active') }}</th>
                  <th>{{ __('users.created_by') }}</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                  @foreach ($users as $user)
                <tr>
                  <!-- <td>{{ $user->avatar }}</td> -->
                  <td>{{ $user->fullname }}</td>
                  <td>{{ $user->username }}</td>
                  <!-- <td style="width:120px">
                      @foreach (arr_permission($user->id) as $key)
                        <li>{{  $key->name }}.</li>
                      @endforeach
                  </td> -->
                  <td>
                    @foreach (arr_role($user->id) as $key)
                      {{  $key->name }} <br/>
                    @endforeach
                  </td>
                  <!-- <td>
                  @if ($user->gender == 1)
                      Nam
                  @elseif ($user->gender == 0)
                      Nữ
                  @else 
                    @if (empty($user->gender))
                      Chưa cập nhật
                    @endif
                  @endif
                  </td> -->
                  <td>{{ $user->email }}</td>
                  
                  <td style="font-size:18px">
                  @if($user->active =='1')
                    <span class="badge bg-success">{{ __('users.active_status') }}</span>
                  @else
                    <span class="badge bg-danger" data-toggle="tooltip" title="{{ __('users.active_now') }}">
                    <a style="text-decoration:none; cursor: pointer;" onclick="activeStatus({{$user->id}})"  data-toggle="modal" data-target="#active">
                    {{ __('users.not_active') }}
                    </a>
                    </span>
                    <div class="modal fade" id="active"  role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-body " style="background-image: url({{ asset('dist/img/agree.png') }}); background-repeat: no-repeat; background-size: 130px; padding-left: 130px;">
                          <h3 class="card-title modal-title w-100" style="margin-bottom: 20px;">{{ __('users.user_activated') }}</h3>
                          <form method="post" id="activeForm" action="">
                              @csrf
                              @method('PUT')
                              <input type="hidden" name="id" id="id">
                              <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
                              <i class="fa fa-times" aria-hidden="true"></i>
                                  {{ __('users.cancel') }}
                              </button>
                              <button type="submit" name="" class="btn btn-success" data-dismiss="modal" onclick="formActiveSubmit()">
                              <i class="fa fa-check" aria-hidden="true"></i>
                                {{ __('users.btn_active') }}
                              </button>
                          </form>
                          </div>
                      </div>
                    </div>
                  </div>
                  @endif
                  </td>
                  <td>
                    @if (isset($user->created_by))
                    {{ user_name($user->created_by) }}
                    @else
                     {{ __('users.self_created_system') }}
                    @endif
                  </td>
                  <td>
                  <a href="{{ route('user.show', $user->id) }}" > 
                      <i data-toggle="tooltip" title="{{ __('users.tooltip_view') }}" style="text-align: right;" class="fa fa-eye" aria-hidden="true"></i>
                  </a>| 
                    <a href="{{ route('user.edit',$user->id) }}"> 
                      <i data-toggle="tooltip" title="{{ __('users.tooltip_edit') }}" style="text-align: right;" class="	fa fa-pencil-square-o" aria-hidden="true"></i>
                    </a>  
                    | 
                    <a href="javascript(0);" onclick="deleteData({{$user->id}})"  style="color:red" data-toggle="modal" data-target="#confirm" > 
                      <i data-toggle="tooltip" title="{{ __('users.tooltip_delete') }}" style="text-align: right;" class="fa fa-trash-o" aria-hidden="true"></i>
                    </a>
                    <div class="modal fade" id="confirm"  role="dialog" aria-labelledby="myModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-body " style="background-image: url({{ asset('dist/img/delete.jpg') }}); background-repeat: no-repeat; background-size: 130px; padding-left: 130px;">
                          <h3 class="card-title modal-title w-100" style="margin-bottom: 20px;">{{ __('users.user_delete') }}</h3>
                          <form method="post" id="deleteForm" action="">
                              @csrf
                              @method('DELETE')
                              <input type="hidden" name="id" id="id">
                              <button data-dismiss="modal" aria-label="Close" class="btn btn-outline-secondary">
                              <i class="fa fa-times" aria-hidden="true"></i>
                                  {{ __('users.cancel') }}
                              </button>
                              <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                                {{ __('users.delete') }}
                              </button>
                          </form>
                          </div>
                      </div>
                    </div>
                  </div>
                  </td>
                </tr>
                @endforeach
                </tbody>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
<!-- /.content-wrapper -->
@include('user.create')
<!-- /.modal -->

@endsection
@push('css')
<link rel="stylesheet" href="{{ asset('plugins/datatables/dataTables.bootstrap4.css') }}">
@endpush

@push('js')
<script type="text/javascript">
  function deleteData(id)
   {
      var id = id;
      var url = '{{ route("user.destroy", ":id") }}';
      url = url.replace(':id', id);
      $("#id").val(id);
      $("#deleteForm").attr('action', url);
    }

    function formSubmit()
    {
      $("#deleteForm").submit();
    }

  function activeStatus(id)
   {
      var id = id;
      var url = '{{ route("activeStatus", ":id") }}';
      url = url.replace(':id', id);
      $("#id").val(id);
      $("#activeForm").attr('action', url);
    }

     function formActiveSubmit()
     {
        $("#activeForm").submit();
     }
     
</script>
@endpush